version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    # Newer versions of lychee cause the exclude-path to not take effect.
    ignore:
      - dependency-name: "lycheeverse/lychee-action"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
