name: "Check formatting and linting"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: "just check"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17 # v1.7.0
        with:
          python-version: "3.11"
          install-just: true
          install-uv: true
          cache: uv

      - name: Check formatting, linting, and import sorting
        run: just check
